### ISSUE TITLE
VBox mouse wheel (up) acts like browser back button.

### ISSUE THREAD

**Issue by mrT55** [project-trident/trident-core#16] opened 2018-09-06 23:13 UTC
I installed: Trident-x64-20180831.iso  as guest OS in a VBox vm.
ran:  trueos-update upgrade   (done on 9/4/2018)

The mouse wheel when rolling UP will act like the 'back' button in konqueror, firefox, and falkon browsers.
It is a bit inconsistent as to how far 'back' the mouse wheel-up will go.
This issue happens in both lumina and kde desktop's.

This mouse issue does not exist in an older release (TrueOS-Desktop-18.03) with the same VBox configuration.

It was discovered the Trident insaller configured /etc/X11/xorg.conf
w/o a keyboard and mouse input sections. I copied the xorg.conf from the vm trueos-Desktop-18.03
and reboot. However the mouse issue remains.

Trident (this is where the mouse was having issues) version info:
```
uname -a
   FreeBSD TridentD01 12.0-CURRENT FreeBSD 12.0-CURRENT #0: Fri Aug 31 09:12:30 UTC 2018
        root@poseidon:/usr/obj/usr/src_tmp/amd64.amd64/sys/GENERIC  amd64

trident-core-201808290904
trueos-libqt5-20180529
trueos-libsh-201706210952
desktop-file-utils-0.23
plasma5-plasma-desktop-5.12.5_3
lumina-1.4.2_201808300852
lumina-core-1.4.2_201808300852
lumina-coreutils-1.4.2_201808300852

xorg-7.7_3
xorg-apps-7.7_2
xorg-drivers-7.7_5
xorg-libraries-7.7_2
xorg-minimal-7.5.2_2
xorg-server-1.18.4_9,1
xorgproto-2018.4

kde-baseapps-18.08.0
kdelibs-kde4-4.14.38_5
kdeutils-18.08.0
kf5-kded-5.49.0
kf5-kdelibs4support-5.49.0
kf5-frameworkintegration-5.49.0
kf5-kded-5.49.0
kf5-kinit-5.49.0
kf5-kpackage-5.49.0
kf5-kparts-5.49.0
kf5-kservice-5.49.0
kf5-krunner-5.49.0
kf5-plasma-framework-5.49.0

falkon-3.0.0_2
firefox-62.0,1
konqueror-18.08.0

```

TrueOS-Desktop-18.03 (In this version the mouse is working OK) version info
```
OS git branch ……………………………………………………………………………………… trueos-stable-18.03
OS git revision ………………………………………………………………………………… fa797a5a3
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… STABLE
TrueOS version …………………………… TrueOS-Desktop-201803131015

virtualbox-ose-additions-5.2.6_1.
trueos-desktop-201803131015
trueos-core-201803131015
trueos-utils-201710251127
trueos-utils-qt5-201803051002

linux-c6-xorg-libs-7.4_10
xorg-drivers-7.7_5
xorg-server-1.18.4_6,1

X.Org X Server 1.18.4
Release Date: 2016-07-19
[    50.938] X Protocol Version 11, Revision 0
[    50.938] Build Operating System: FreeBSD 12.0-CURRENT amd64
[    50.938] Current Operating System: FreeBSD trueos-8503 12.0-CURRENT FreeBSD 12.0-CURRENT #26 fa797a5a3(trueos-stable-18.03): Mon Mar 26 00:24:47 UTC 2018     root@chimera:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64
[    50.938] Build Date: 08 March 2018  02:00:13PM
[    50.938]
[    50.938] Current version of pixman: 0.34.0

/usr/local/bin/konqueror was installed by package kde-baseapps-4.14.3_3
firefox-61.0.2,1
chromium-63.0.3239.132
falkon-3.0.0
```

Using VBox (both Trueos-Desktop and Trident use this VBox configuration):
```
   config:
      Shared Clipboard and Drag'n'Drop: Bidirectional
      system
          Motherboard tab
             Base Mem: 7024 MB
             Chipset: ICH9
             Pointing Device: PS/2 Mouse
             Extended Features: [x] Enable I/O APIC
                                [x] Enable EFI
          Processor tab
             Processors: 2
             Execution Cap: 90%
             Extended Features: [ ] Enable PAE/NX

          Acceleration tab
             Paravirtualization interface: KVM
             Hardware Virtualization: [x] Enable VT-x/AMD-V
                                      [x] Enable Nested Paging

       Display
          Screen tab
             Vid Mem: 123 MB
             Monitor count: 1
             Scale Factor:  100 %
             Acceleration: [x] Enable 3D Acceleration
                           [ ] Enable 2D Acceleration

          Remote Display tab
             [x] Enable Server
              (all other settings on this tab are default values.)

       Storage
          Controller: SATA       Type: AHCI
             xxx.vdi   virtual HD
```

**Comment by beanpole135** [comment] 2018-09-11 20:09
This has been noticed on TrueOS since 2017, and appears to be a bad interaction between VirtualBox (host) and the moused daemon (FreeBSD guest) which results in additional mouse button 1 (left click) and mouse button 7 (back) events getting generated while using the scroll wheel on the mouse.

This can easily be reproduced/tested by installing the "xev" utility and running it. While it is running, place the mouse over the testing window and then scroll the mouse wheel.

I am unaware of any known fixes for this on FreeBSD at the present time.

**Comment by Troub274** [comment] 2018-11-27 15:40
This is highly irritating and I can't believe I'm the only one with this problem.  Who do we contact to fix it? is it VirtualBox or FreeBSD Who is the responsible project?

**Comment by beanpole135** [comment] 2019-04-02 13:22
I found a work-around for this issue and committed it to 18.12-U8.
Seems that turning off the "moused" service in virtualbox guest sessions prevent that mouse-click duplication/error issue.

**Closed by beanpole135** 2019-04-02 13:22 UTC
